# Generated by Django 2.2.12 on 2021-01-08 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('num', models.CharField(max_length=18, primary_key=True, serialize=False, unique=True, verbose_name='工号')),
                ('password', models.CharField(default='000000', max_length=30, verbose_name='密码')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('gender', models.CharField(max_length=5, verbose_name='性别')),
                ('age', models.IntegerField(default=0, verbose_name='年龄')),
                ('edu', models.CharField(default='文盲', max_length=20, verbose_name='学历')),
                ('ethnic_groups', models.CharField(default='汉', max_length=20, verbose_name='民族')),
                ('address', models.CharField(default='无', max_length=20, verbose_name='地址')),
                ('tele', models.CharField(default='无', max_length=20, verbose_name='联系电话')),
                ('position', models.CharField(default='待入职', max_length=10, verbose_name='岗位')),
                ('Is_manage', models.BooleanField(default=False, verbose_name='是否为管理员')),
                ('brief_introduction', models.CharField(blank=True, max_length=500, null=True, verbose_name='简介')),
            ],
            options={
                'verbose_name_plural': '职员表',
                'verbose_name': '职员表',
            },
        ),
        migrations.CreateModel(
            name='Step_parent',
            fields=[
                ('num', models.CharField(max_length=18, primary_key=True, serialize=False, unique=True, verbose_name='身份证号')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('gender', models.CharField(max_length=5, verbose_name='性别')),
                ('age', models.IntegerField(default=0, verbose_name='年龄')),
                ('edu', models.CharField(max_length=20, verbose_name='学历')),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='月收入')),
                ('married', models.BooleanField(default=False, verbose_name='是否已婚')),
                ('Has_child', models.BooleanField(default=False, verbose_name='是否已有子女')),
                ('address', models.CharField(default='无', max_length=20, verbose_name='地址')),
                ('tele', models.CharField(default='无', max_length=20, verbose_name='联系电话')),
            ],
            options={
                'verbose_name_plural': '领养人资料表',
                'verbose_name': '领养人资料表',
            },
        ),
        migrations.CreateModel(
            name='To_doList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500, verbose_name='内容')),
                ('Is_completed', models.BooleanField(default=False, verbose_name='是否完成')),
                ('topic', models.CharField(default='事件', max_length=500, verbose_name='主题')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='App.Employee')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publisher', to='App.Employee')),
            ],
            options={
                'verbose_name_plural': '待办表',
                'verbose_name': '待办表',
            },
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('num', models.CharField(max_length=18, primary_key=True, serialize=False, unique=True, verbose_name='身份证号')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('gender', models.CharField(max_length=5, verbose_name='性别')),
                ('age', models.IntegerField(default=0, verbose_name='年龄')),
                ('edu', models.CharField(default='文盲', max_length=20, verbose_name='教育水平')),
                ('enter_time', models.DateField(default='2000.1.1', verbose_name='入院时间')),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='体重/kg')),
                ('height', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='身高/cm')),
                ('temperature', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='体温')),
                ('right_sight', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='右眼视力')),
                ('left_sight', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='左眼视力')),
                ('Is_adopted', models.BooleanField(default=False, verbose_name='已被领养')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.Employee')),
            ],
            options={
                'verbose_name_plural': '儿童表',
                'verbose_name': '儿童表',
            },
        ),
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('num', models.CharField(max_length=18, primary_key=True, serialize=False, unique=True, verbose_name='申请编号')),
                ('content', models.CharField(max_length=500, verbose_name='内容')),
                ('Is_audited', models.BooleanField(default=False, verbose_name='是否已审核')),
                ('applicant', models.CharField(default='申请者', max_length=18, verbose_name='申请者')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Employee')),
            ],
            options={
                'verbose_name_plural': '审核表',
                'verbose_name': '审核表',
            },
        ),
    ]
