# Generated by Django 2.2.12 on 2021-01-10 21:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_to_dolist_publish_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='to_dolist',
            name='Publish_time',
            field=models.TimeField(default=datetime.datetime(2021, 1, 10, 21, 21, 17, 855520), verbose_name='发布时间'),
        ),
    ]
