# Generated by Django 2.2.12 on 2021-01-11 18:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_auto_20210111_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='to_dolist',
            name='Publish_time',
            field=models.TimeField(default=datetime.datetime(2021, 1, 11, 18, 58, 36, 676475), verbose_name='发布时间'),
        ),
    ]
