# Generated by Django 2.2.12 on 2021-01-11 20:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_auto_20210111_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='to_dolist',
            name='Publish_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 11, 20, 8, 16, 381129), verbose_name='发布时间'),
        ),
    ]
