# Generated by Django 2.2.12 on 2021-01-12 12:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_auto_20210112_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='step_parent',
            name='is_sender',
            field=models.BooleanField(default=False, verbose_name='是否已发送'),
        ),
        migrations.AlterField(
            model_name='to_dolist',
            name='Publish_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 12, 12, 12, 37, 620780), verbose_name='发布时间'),
        ),
    ]
