# Generated by Django 2.2.12 on 2021-01-12 12:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_auto_20210112_1212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='step_parent',
            old_name='is_sender',
            new_name='is_send',
        ),
        migrations.AlterField(
            model_name='to_dolist',
            name='Publish_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 12, 12, 13, 2, 968169), verbose_name='发布时间'),
        ),
    ]
