# Generated by Django 2.2.12 on 2021-01-12 12:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_auto_20210112_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='to_dolist',
            name='Publish_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 12, 12, 33, 35, 975867), verbose_name='发布时间'),
        ),
    ]
