# Generated by Django 2.2.12 on 2021-01-12 12:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_auto_20210112_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='num',
            field=models.AutoField(max_length=18, primary_key=True, serialize=False, unique=True, verbose_name='申请编号'),
        ),
        migrations.AlterField(
            model_name='to_dolist',
            name='Publish_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 12, 12, 38, 6, 872071), verbose_name='发布时间'),
        ),
    ]
