# Generated by Django 2.2.12 on 2021-01-12 12:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_auto_20210112_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Step_parent'),
        ),
        migrations.AlterField(
            model_name='to_dolist',
            name='Publish_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 12, 12, 39, 25, 552601), verbose_name='发布时间'),
        ),
    ]
