# Generated by Django 2.2.12 on 2021-01-12 12:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_auto_20210112_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='员工', to='App.Employee'),
        ),
        migrations.AlterField(
            model_name='audit',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='管理员', to='App.Employee'),
        ),
        migrations.AlterField(
            model_name='to_dolist',
            name='Publish_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 12, 12, 41, 27, 406066), verbose_name='发布时间'),
        ),
    ]
